routes/web.php
<?php

// Route::redirect('/', '/login');

Route::redirect('/home', '/admin');
Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/profile/{slug}', 'WelcomeController@showpage');
Route::get('/about', 'WelcomeController@showabout');
Route::get('/member', 'WelcomeController@showmember');
Route::get('/result/{research}', 'WelcomeController@showdetailresearch');
Route::get('/article/{article}', 'WelcomeController@showdetailarticle');
// Route buat contoh article
Route::get('/article', 'WelcomeController@showarticle')->name('edusection.index');
Route::get('/article/subarticle/{id}', 'WelcomeController@showsubarticle')->name('subarticle.ind');
Route::get('/article/subarticle/detail/{subarticle}', 'WelcomeController@showdetail')->name('detailsub.show');
// Route buat supportus
Route::get('/support', 'WelcomeController@support');

Auth::routes(['register' => false]);
Route::get('logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('/');
})->name('logout');

Route::get('/search','WelcomeController@search');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');


    Route::resource('roles', 'RolesController');
;

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('contributes/destroy', 'ContributeController@massDestroy')->name('contributes.massDestroy');

    Route::resource('contributes', 'ContributeController');

    Route::delete('requests/destroy', 'RequestsController@massDestroy')->name('requests.massDestroy');

    Route::resource('requests', 'RequestsController');

    // Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    // Route::resource('products', 'ProductsController');

    // Route::resource('articles', 'ArticleController');

    // Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');


    // Route::resource('subarticles', 'SubArticleController');
    Route::get('subarticles/creates/{id}', 'SubArticleController@creates')->name('subarticles.creates');
    Route::get('subarticles/show/{subarticle}/detail', 'SubArticleController@show')->name('subarticles.shows');
    Route::get('subarticles/{subarticle}/edit', 'SubArticleController@edit')->name('subarticles.edit');
    Route::post('subarticles/store', 'SubArticleController@store')->name('subarticles.store');
    Route::get('subarticles/detail/{id}', 'SubArticleController@index')->name('subarticles.indexs');
    Route::post('subarticles/update', 'SubArticleController@update')->name('subarticles.update');
    Route::get('subarticles/{id}', 'SubArticleController@index')->name('subarticles.destroy');
    Route::delete('subarticles/destroy', 'SubArticleController@massDestroy')->name('subarticles.massDestroy');
    Route::resource('subarticles', 'SubArticleController');



    Route::resource('medias', 'MediaController');
    Route::delete('medias/destroy', 'MediaController@massDestroy')->name('medias.massDestroy');

    Route::resource('footers', 'FooterController');
    Route::delete('footers/destroy', 'FooterController@massDestroy')->name('footers.massDestroy');

    Route::resource('homes', 'HomePageController');
    Route::delete('homes/destroy', 'HomePageController@massDestroy')->name('homes.massDestroy');


    Route::resource('sliders', 'SliderController');
    Route::delete('sliders/destroy', 'SliderController@massDestroy')->name('sliders.massDestroy');

    Route::group(['prefix' => 'laravel-filemanager','middleware' => ['auth']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});


});
Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});

resources/views/partials/about.blade.php
@extends('partials.layout')

@section('content')
	<div id="about-us-1" class="prim-color">
		<div class="container py-5">
			<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
				<li class="nav-item">
					<a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-about-us" role="tab" aria-controls="pills-home" aria-selected="true">About Us</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-our-mission" role="tab" aria-controls="pills-profile" aria-selected="false">Our Mission</a>
				</li>
			</ul>
			<div class="tab-content" id="pills-tabContent">
				<div class="tab-pane fade show active" id="pills-about-us" role="tabpanel" aria-labelledby="pills-home-tab">
					<div class="row">
						<div class="col-md-4 pt-3">
							<div class="logo"></div>
						</div>
						<div class="col-md-8 pt-3 desc-text">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="pills-our-mission" role="tabpanel" aria-labelledby="pills-profile-tab">
					<div class="row">
						<div class="col-md-4 pt-3">
							<div class="logo"></div>
						</div>
						<div class="col-md-8 pt-3 desc-text">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div id="team" class="acc-color">
		<div class="container px-5 text-center pt-5">
			<h5 class="small-text">Lets Meet</h5>
			<h1 class="display-4 white-text text-center">Our Team</h1>
			<div class="row pb-5">
				<div class="col-md-4 my-4 px-5">
					<div class="img-hover-zoom img-hover-zoom--colorize">
						<img src="https://picsum.photos/800/800?image=342" width="100%">
						<div class="caption-name">John Doe</div>
						<div class="caption-desc">Head Manager</div>
					</div>
				</div>
				<div class="col-md-4 my-4 px-5">
					<div class="img-hover-zoom img-hover-zoom--colorize">
						<img src="https://picsum.photos/800/800?image=342" width="100%">
						<div class="caption-name">Susan Lee</div>
						<div class="caption-desc">Manager</div>
					</div>
				</div>
				<div class="col-md-4 my-4 px-5">
					<div class="img-hover-zoom img-hover-zoom--colorize">
						<img src="https://picsum.photos/800/800?image=342" width="100%">
						<div class="caption-name">Harold Dave</div>
						<div class="caption-desc">Supervisor</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
@endsection

resources/views/partials/detailevent.blade.php
@extends('partials.header')
@extends('partials.nav')
<div class="container pt-5 mt-5">
    <div class="mt-5 pt-5 mb-5 pb-5">
            <h1>{{ $event->title }}</h1>
            <span><b> {{ \Carbon\Carbon::parse($event->created_at)->format('D, d F Y') }} </b></span><br>
            <img class="img-fluid " style="height:350px;object-fit: cover;" src="{{ $event->image }}" alt=""><br>

            {!! $event->content !!}
    </div>
</div>
@extends('partials.footer')

resources/views/partials/detailnews.blade.php
@extends('partials.header')
@extends('partials.nav')
<div class="container pt-5 mt-5">
    <div class="mt-5 pt-5 mb-5 pb-5">
            <h1>{{ $news->title }}</h1>
            <span><b> {{ \Carbon\Carbon::parse($news->created_at)->format('D, d F Y') }} </b></span><br>
            <img class="img-fluid  pt-3 pb-3" style="height:350px;object-fit: cover;    " src="{{ $news->image }}" alt="">
            {!! $news->content !!}
    </div>
</div>
@extends('partials.footer')

resources/views/partials/detailprogram.blade.php
@extends('partials.header')
@extends('partials.nav')
<div class="container pt-5 mt-5">
    <div class="mt-5 pt-5 mb-5 pb-5">
            <h1>{{ $program->title }}</h1>
            <span><b> {{ \Carbon\Carbon::parse($program->created_at)->format('D, d F Y') }} </b></span><br>
            {!! $program->content !!}
            <br>
            <a href="{{ $program->attachment }}" download>Download Attachment This Program</a>
    </div>
</div>
@extends('partials.footer')

resources/views/partials/event1.blade.php
@extends('partials.header')
@extends('partials.nav')

<div class="jumbotron paral paralsec mt-5">
        <h1 class="display-2 text-white mt-5 text-center">All Event
            </h1>
        </div>
    <!-- end of header -->
<div class="container">
<div class="row">
    <div class="col-12">
        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">training</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">seminar</a>
          </div>
        </nav>
        <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
              <!--  row list evet -->
            <div class="row" id="image">
                @foreach ($trainings as $training)
                <div class="col-sm-12">
                    <div class="col-xl-6 col-sm-12">
                        <div class=" bg-faded">
                            <div class="card-body">
                              <div class="row">
                        <div class="col-4">
                          <img src="{{ asset('img/6.jpg') }}" alt="" class="rounded img-fluid" />
                                </div>
                                 <div class="col-8">
                                        <h5>
                                            <a class="text-bluealter" href="/event/detail/{{ $training->id }}">{{ $training->title }}</a>  </h5>
                                            <small><i class="far fa-clock"></i> 07/07/2020</small>
                                        <p>
                                            {!! substr($training->content,0,110) !!}
                                        </p>
                                        <!-- Split button -->
                                       <div class="btn-group">

                                            <p>[ <a href="/event/detail/{{ $training->id }}" class="text-danger">More</a> ]</p>
                                        </div>
                  <!-- End Button -->
                                    </div>
                                    <!-- End columns 7 -->
                              </div>
                            </div>
                          </div>
                    </div>
                    </div>
                @endforeach
              </div>
              <!-- end list event -->
          </div>

          <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            <!--  row list evet -->
            <div class="row" id="image">
                    @foreach ($seminars as $seminar)
                    <div class="col-sm-12">
                        <div class="col-xl-6 col-sm-12">
                            <div class=" bg-faded">
                                <div class="card-body">
                                  <div class="row">
                            <div class="col-4">
                              <img src="{{ asset('img/6.jpg') }}" alt="" class="rounded img-fluid" />
                                    </div>
                                     <div class="col-8">
                                            <h5>
                                                <a class="text-bluealter" href="/event/detail/{{ $seminar->id }}">{{ $seminar->title }}</a>  </h5>
                                                <small><i class="far fa-clock"></i> 07/07/2020</small>
                                            <p>
                                                {!! substr($seminar->content,0,110) !!}
                                            </p>
                                            <!-- Split button -->
                                           <div class="btn-group">

                                                <p>[ <a href="/event/detail/{{ $seminar->id }}" class="text-danger">More</a> ]</p>
                                            </div>
                      <!-- End Button -->
                                        </div>
                                        <!-- End columns 7 -->
                                  </div>
                                </div>
                              </div>
                        </div>
                        </div>
                    @endforeach
            </div>
            <!-- end list event -->
          </div>
        </div>

        <!-- MOdal Image -->
        {{-- <div class="modal fade " id="imagemodal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <img class="modal-img img-fluid" />
                </div>
            </div>
        </div> --}}
        <!-- end of modal image -->
    </div>
</div>
</div>
@extends('partials.footer')

resources/views/partials/footer.blade.php
    <footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          LexLite
          <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Team</a></li>
            <li><a class="text-muted" href="#">Locations</a></li>
            <li><a class="text-muted" href="#">Privacy</a></li>
            <li><a class="text-muted" href="#">Terms</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Features</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Cool stuff</a></li>
            <li><a class="text-muted" href="#">Random feature</a></li>
            <li><a class="text-muted" href="#">Team feature</a></li>
            <li><a class="text-muted" href="#">Stuff for developers</a></li>
            <li><a class="text-muted" href="#">Another one</a></li>
            <li><a class="text-muted" href="#">Last time</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Resource</a></li>
            <li><a class="text-muted" href="#">Resource name</a></li>
            <li><a class="text-muted" href="#">Another resource</a></li>
            <li><a class="text-muted" href="#">Final resource</a></li>
          </ul>
        </div>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6972b7bfd3.js" crossorigin="anonymous"></script>
    <script src="assets/js/style.js"></script>
  </body>
</html>

resources/views/partials/media.blade.php
@extends('partials.header')
@extends('partials.nav')
<div class="mt-3 mb-4">
        <h1 class="display-2 text-white mt-5 text-center">All New Media you Select
            </h1>
        </div>
    <!-- end of header -->
<div class="container">
<div class="row">
    @foreach ($medias as $media)
    <div class="col-xl-6 col-sm-12">
        <div class=" bg-faded">
            <div class="card-body">
              <div class="row">
        <div class="col-4">
            <img alt="" class="rounded img-fluid" src="{{ $media->image }}" style=" height: 250px;object-fit: cover;">
        </div>
        <!-- start card content -->
        <div class="col-8">
            <h5>
                <a class="text-bluealter" href="{{ $media->id }}">{{ $media->title }}</a>
                <small><i class="far fa-clock"></i> {{ \Carbon\Carbon::parse($media->created_at)->format('d F, Y') }}</small>
                <p>{!! substr($media->content,0,200) !!}....</p>
                <div class="btn-group">
                    <p>
                    <a class="text-danger" href="{{ $media->id }}">Detail news</a>
                    </p>
                </div>
            </div>

        </div>
  </div>
</div>
</div>
            <!-- end card -->
            @endforeach

      </div>

</div>
</div>
@extends('partials.footer')

resources/views/partials/menu.blade.php
<div class="sidebar prim-color">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <a href="{{ route("admin.home") }}" class="nav-link">
          <i class="nav-icon fas fa-tachometer-alt">
          </i>
          {{ trans('global.dashboard') }}
        </a>
      </li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle">
          <i class="fas fa-users nav-icon">
          </i>
          {{ trans('global.userManagement.title') }}
        </a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
              <i class="fas fa-unlock-alt nav-icon">
              </i>
              {{ trans('global.permission.title') }}
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
              <i class="fas fa-briefcase nav-icon">
              </i>
              {{ trans('global.role.title') }}
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
              <i class="fas fa-user nav-icon">
              </i>
              {{ trans('global.user.title') }}
            </a>
          </li>
        </ul>
      </li>
      {{--  <li class="nav-item">
        <a href="{{ route("admin.medias.index") }}" class="nav-link {{ request()->is('admin/medias') || request()->is('admin/medias/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          {{ trans('global.article.title') }}
        </a>
      </li>  --}}
      {{-- <li class="nav-item">
        <a href="{{ route("admin.resources.index") }}" class="nav-link {{ request()->is('admin/resources') || request()->is('admin/resources/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          {{ trans('global.article.title') }}  resource
        </a>
      </li> --}}
      <li class="nav-item">
        <a href="{{ route("admin.contributes.index") }}" class="nav-link {{ request()->is('admin/contributes') || request()->is('admin/contributes/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          Kontributor User
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route("admin.medias.index") }}" class="nav-link {{ request()->is('admin/medias') || request()->is('admin/medias/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          Media
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route("admin.requests.index") }}" class="nav-link {{ request()->is('admin/requests') || request()->is('admin/requests/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          Request Content
        </a>
      </li>
      {{-- <li class="nav-item">
        <a href="{{ route("admin.homes.index") }}" class="nav-link {{ request()->is('admin/homes') || request()->is('admin/homes/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          {{ trans('global.home.title') }}
        </a>
      </li> --}}
      {{-- <li class="nav-item">
        <a href="{{ route("admin.pages.index") }}" class="nav-link {{ request()->is('admin/pages') || request()->is('admin/pages/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          {{ trans('global.page.title') }}
        </a>
      </li> --}}
      {{-- <li class="nav-item">
        <a href="{{ route("admin.partners.index") }}" class="nav-link {{ request()->is('admin/partners') || request()->is('admin/partners/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          {{ trans('global.partner.title') }}
        </a>
      </li> --}}
      <li class="nav-item">
        <a href="{{ route("admin.sliders.index") }}" class="nav-link {{ request()->is('admin/sliders') || request()->is('admin/sliders/*') ? 'active' : '' }}">
          <i class="fas fa-cogs nav-icon">
          </i>
          {{ trans('global.slider.title') }}
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route("logout") }}" class="nav-link">
          <i class="nav-icon fas fa-sign-out-alt">
          </i>
          {{ trans('global.logout') }}
        </a>
      </li>
    </ul>
    <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
      <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
    </div>
    <div class="ps__rail-y" style="top: 0px; height: 1869px; right: 0px;">
      <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 415px;"></div>
    </div>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

resources/views/partials/news.blade.php
@extends('partials.header')
@extends('partials.nav')
<div class="jumbotron paral paralsec mt-5">
        <h1 class="display-2 text-white mt-5 text-center">News
            </h1>
        </div>
    <!-- end of header -->
<div class="container">
<div class="row">
      <div class="col-12">
              <div class="row">
                      <div class="container">
                              <div class="row">
                                  <div class="col-12">
                                      <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                                          <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Perbanas</a>
                                          <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Collaboration</a>
                                        </div>
                                      </nav>
                                      <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                                            <!--  row list evet -->
                                                
                                          <div class="row" id="image">
                                                @foreach ($perbanas as $perbanasitem)
                                            <div class="col-sm-12">
                                                <div class="card w-100 flex-md-row mb-4 shadow-sm h-md-250">
                                                        <div class="card-body w-50 d-flex flex-column align-items-start">
                                                            <h6 class="mb-0">
                                                                <a class="text-dark" href="#">{{ $perbanasitem->title }}</a>
                                                            </h6>
                                                            <div class="mb-1 text-muted small">{{ \Carbon\Carbon::parse($perbanasitem->created_at)->format('d F, Y') }}</div>
                                                            <p class="card-text mb-auto">{!! substr($perbanasitem->content,0,200) !!}....</p>
                                                            <a class="btn btn-outline-success btn-sm" href="/news/{{ $perbanasitem->id }}">Detail News</a>
                                                        </div>
                                                        <img class="card-img-right flex-auto d-none d-lg-block w-50" alt="Thumbnail [200x250]" src="{{ $perbanasitem->image }}" style=" height: 250px;object-fit: cover;">
                                                    </div>
                                           </div>
                                           @endforeach
                                      
                                            </div>
                                            <!-- end list event -->
                                        </div>
                                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                                          <!--  row list evet -->
                                          <div class="row" id="image">
                                                @foreach ($collaboration as $collabitem)
                                                @if ($collabitem = null)
                                                    <p>Oops There is No Latest Data News</p>
                                                @else
                                                    
                                                <div class="col-sm-12">
                                                    <div class="card w-100 flex-md-row mb-4 shadow-sm h-md-250">
                                                            <div class="card-body w-50 d-flex flex-column align-items-start">
                                                                <h6 class="mb-0">
                                                                    <a class="text-dark" href="#">{{ $collabitem->title }}</a>
                                                                </h6>
                                                                <div class="mb-1 text-muted small">{{ \Carbon\Carbon::parse($collabitem->created_at)->format('d F, Y') }}</div>
                                                                <p class="card-text mb-auto">{!! substr($perbanasitem->content,0,200) !!}....</p>
                                                                <a class="btn btn-outline-success btn-sm" href="/news/{{ $collabitem->id }}">Detail News</a>
                                                            </div>
                                                            <img class="card-img-right flex-auto d-none d-lg-block w-50" alt="Thumbnail [200x250]" src="{{ $collabitem->image }}" style=" height: 250px;object-fit: cover;">
                                                </div>
                                               </div>
                                               @endif

                                               @endforeach
                                            
                                          </div>
                                          <!-- end list event -->  
                                        </div>
                                        
                                      </div>
                                      
                                  </div>
                              </div>
                          </div>
                 
                  </div>     <!-- end of list seminars and collabs  -->
      </div>
  </div>
</div>
@extends('partials.footer')

resources/views/partials/report.blade.php
@extends('partials.header')
@extends('partials.nav')
<div class="jumbotron paral paralsec mt-5">
        <h1 class="display-2 text-white mt-5 text-center">report
            </h1>
        </div>
    <!-- end of header -->
<div class="container">
<div class="row">
      <div class="col-sm-12">
        @foreach ($reports as $report)
            
        <!-- start card content -->
            <div class="card w-100 flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body w-50 d-flex flex-column align-items-start">
                    <h6 class="mb-0">
                        <a class="text-dark" href="{{ $report->id }}">{{ $report->title }}</a>
                    </h6>
                    <div class="mb-1 text-muted small">{{ \Carbon\Carbon::parse($report->created_at)->format('d F, Y') }}</div>
                    <p class="card-text mb-auto">{!! substr($report->content,0,200) !!}....</p>
                    <a class="btn btn-outline-success btn-sm" href="{{ $report->id }}">Detail Report</a>
                </div>
                <img class="card-img-right flex-auto d-none d-lg-block w-50" alt="Thumbnail [200x250]" src="{{ $report->image }}" style="width: 200px; height: 250px;">
            </div>
            <!-- end card -->
            @endforeach  
        
      </div>

</div>
</div>
@extends('partials.footer')