routes/web.php
<?php

// Route::redirect('/', '/login');

Route::redirect('/home', '/admin');
Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/profile/{slug}', 'WelcomeController@showpage');
Route::get('/about', 'WelcomeController@showabout');
Route::get('/member', 'WelcomeController@showmember');
Route::get('/result/{research}', 'WelcomeController@showdetailresearch');
Route::get('/article/{article}', 'WelcomeController@showdetailarticle');
// Route buat contoh article
Route::get('/article', 'WelcomeController@showarticle')->name('edusection.index');
Route::get('/article/subarticle/{id}', 'WelcomeController@showsubarticle')->name('subarticle.ind');
Route::get('/article/subarticle/detail/{subarticle}', 'WelcomeController@showdetail')->name('detailsub.show');
// Route buat supportus
Route::get('/support', 'WelcomeController@support');

Auth::routes(['register' => false]);
Route::get('logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('/');
})->name('logout');

Route::get('/search','WelcomeController@search');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');


    Route::resource('roles', 'RolesController');
;

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('contributes/destroy', 'ContributeController@massDestroy')->name('contributes.massDestroy');

    Route::resource('contributes', 'ContributeController');

    Route::delete('requests/destroy', 'RequestsController@massDestroy')->name('requests.massDestroy');

    Route::resource('requests', 'RequestsController');

    // Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    // Route::resource('products', 'ProductsController');

    // Route::resource('articles', 'ArticleController');

    // Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');


    // Route::resource('subarticles', 'SubArticleController');
    Route::get('subarticles/creates/{id}', 'SubArticleController@creates')->name('subarticles.creates');
    Route::get('subarticles/show/{subarticle}/detail', 'SubArticleController@show')->name('subarticles.shows');
    Route::get('subarticles/{subarticle}/edit', 'SubArticleController@edit')->name('subarticles.edit');
    Route::post('subarticles/store', 'SubArticleController@store')->name('subarticles.store');
    Route::get('subarticles/detail/{id}', 'SubArticleController@index')->name('subarticles.indexs');
    Route::post('subarticles/update', 'SubArticleController@update')->name('subarticles.update');
    Route::get('subarticles/{id}', 'SubArticleController@index')->name('subarticles.destroy');
    Route::delete('subarticles/destroy', 'SubArticleController@massDestroy')->name('subarticles.massDestroy');
    Route::resource('subarticles', 'SubArticleController');



    Route::resource('medias', 'MediaController');
    Route::delete('medias/destroy', 'MediaController@massDestroy')->name('medias.massDestroy');

    Route::resource('footers', 'FooterController');
    Route::delete('footers/destroy', 'FooterController@massDestroy')->name('footers.massDestroy');

    Route::resource('homes', 'HomePageController');
    Route::delete('homes/destroy', 'HomePageController@massDestroy')->name('homes.massDestroy');


    Route::resource('sliders', 'SliderController');
    Route::delete('sliders/destroy', 'SliderController@massDestroy')->name('sliders.massDestroy');

    Route::group(['prefix' => 'laravel-filemanager','middleware' => ['auth']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});


});
Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});

app/Media.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Media extends Model
{
    //
    use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',
        'image',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/Admin/MediaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMediaRequest;
use App\Http\Requests\StoreMediaRequest;
use App\Http\Requests\UpdateMediaRequest;
use App\Media;
class MediaController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('media_access'), 403);

        $media = Media::all();

        return view('admin.medias.index', compact('media'));
    }

    public function medialatest()
    {
        $medialatest = Media::latest()->get();
        return view('admin.media.latestmedia', compact('medialatest'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('media_create'), 403);

        return view('admin.medias.create');
    }

    public function store(StoreMediaRequest $request)
    {
        abort_unless(\Gate::allows('media_create'), 403);

        $medias = Media::create($request->all());

        return redirect()->route('admin.medias.index');
    }

    public function edit(Media $media)
    {
        abort_unless(\Gate::allows('media_edit'), 403);

        return view('admin.medias.edit', compact('media'));
    }

    public function update(UpdateMediaRequest $request, Media $media)
    {
        abort_unless(\Gate::allows('media_edit'), 403);

        $media->update($request->all());

        return redirect()->route('admin.medias.index');
    }

    public function show(Media $media)
    {
        abort_unless(\Gate::allows('media_show'), 403);

        return view('admin.medias.show', compact('media'));
    }

    public function destroy(Media $media)
    {
        abort_unless(\Gate::allows('media_delete'), 403);

        $media->delete();

        return back();
    }

    public function massDestroy(MassDestroyMediaRequest $request)
    {
        Media::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}

resources/views/admin/medias/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
  <div class="card-header">
    {{ trans('global.create') }} {{ trans('global.article.title_singular') }}
  </div>

  <div class="card-body">
    <form action="{{ route("admin.medias.store") }}" method="POST" enctype="multipart/form-data">
      @csrf

      <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
        <label for="name">{{ trans('global.article.fields.title') }}*</label>
        <input type="text" id="name" name="title" class="form-control" value="{{ old('title', isset($media) ? $media->title : '') }}">

        @if($errors->has('title'))
        <em class="invalid-feedback">
        {{ $errors->first('title') }}
        </em>
        @endif

      </div>

      <div class="form-group">
        <div class="input-group">
          <span class="input-group-btn white-text">
            <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
              <i class="fa fa-picture-o"></i> Choose
            </a>
          </span>
          <input id="thumbnail" class="form-control" type="text" name="image">
        </div>
        <img id="holder" style="margin-top:15px;max-height:100px;">

      </div>

      <div class="form-group">
        <textarea class="my-editor"></textarea>
      </div>

      <div>
        <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
      </div>

    </form>
  </div>
</div>
@endsection

@section('scripts')

<script src="{{ url('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
<script>
  var route_prefix = "{{ url('laravel-filemanager') }}";
  $('#lfm').filemanager('image', {prefix: route_prefix});
</script>


<script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
var editor_config = {
  path_absolute : "/",
  selector: "textarea.my-editor",
  plugins: [
    "advlist autolink lists link image charmap print preview hr anchor pagebreak",
    "searchreplace wordcount visualblocks visualchars code fullscreen",
    "insertdatetime media nonbreaking save table contextmenu directionality",
    "emoticons template paste textcolor colorpicker textpattern"
  ],

  toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",

  relative_urls: false,
  file_browser_callback : function(field_name, url, type, win) {
    var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
    var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
    var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
    if (type == 'image') {
      cmsURL = cmsURL + "&type=Images";
    } else {
      cmsURL = cmsURL + "&type=Files";
    }
    tinyMCE.activeEditor.windowManager.open({
      file : cmsURL,
      title : 'Filemanager',
      width : x * 0.8,
      height : y * 0.8,
      resizable : "yes",
      close_previous : "no"
    });
  }
};
tinymce.init(editor_config);
</script>
@endsection

resources/views/admin/medias/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.user.title_singular') }}
    </div>

    <div class="card-body">
      <form action="{{ route("admin.medias.update", [$media->id]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.article.fields.title') }}*</label>
                <input type="text" id="name" name="title" class="form-control" value="{{ old('title', isset($media) ? $media->title : '') }}">
                @if($errors->has('title'))
                    <em class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </em>
                @endif
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                      <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                        <i class="fa fa-picture-o"></i> Choose
                      </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="image" value="{{ old('image', isset($media) ? $media->image : '') }}">
                  </div>
                  <img id="holder" style="margin-top:15px;max-height:100px;">
                  <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
                  <script>
                  var route_prefix = "http://localhost:8000/laravel-filemanager";
 $('#lfm').filemanager('image', {prefix: route_prefix});
                </script>
                </div>

            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/medias/index.blade.php
@extends('layouts.admin')

@section('content')

@can('media_create')
<div style="margin-bottom: 10px;" class="row">
  <div class="col-lg-12">
    @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
    </div>
    @endif
    @if ($message = Session::get('warning'))
    <div class="alert alert-success alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
    </div>
    @endif
    <a class="btn btn-success" href="{{ route("admin.medias.create") }}">
      Add  Category Post
    </a>
  </div>
</div>
@endcan

<div class="card">
  <div class="card-header">
    Post Category List
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class=" table table-bordered table-striped table-hover datatable">
        <thead>
          <tr>
            <th width="10">
            </th>
            <th>
              {{ trans('global.article.fields.title') }}
            </th>
            <th>
              {{ trans('global.article.fields.image') }}
            </th>
            {{--  <th>
              {{ trans('global.article.fields.content') }}
            </th>  --}}
            <th>
              &nbsp; Option
            </th>
          </tr>
        </thead>
        <tbody>
          @foreach($media as $key => $media)
          <tr data-entry-id="{{ $media->id }}">
            <td>
            </td>
            <td>
              {{ $media->title ?? '' }}
            </td>
            <td>
              <img height="200" src=" {{ $media->image ?? '' }}" alt="">
            </td>
            {{--  <td>
              {!! substr( $media->content,0,150 ?? '') !!}
            </td>  --}}
            <td>
              @can('media_show')
              <a class="btn btn-xs btn-primary" href="{{ route('admin.medias.show', $media->id) }}">
                Show
              </a>
              @endcan
              <a class="btn btn-xs btn-success" href="{{ route('admin.subarticles.indexs', $media->id) }}">
                View All Article
              </a>
              @can('media_edit')
              <a class="btn btn-xs btn-info" href="{{ route('admin.medias.edit', $media->id) }}">
                {{ trans('global.edit') }}
              </a>
              @endcan
              @can('media_delete')
              <form action="{{ route('admin.medias.destroy', $media->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
              </form>
              @endcan
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection

@section('scripts')
@parent
<script>
$(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.medias.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
        return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')
        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }
        }).done(function () { location.reload() })
      }
    }
  }

  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

  @can('media_delete')
  dtButtons.push(deleteButton)
  @endcan
  
  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})
</script>

@endsection

resources/views/admin/medias/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.user.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.article.fields.title') }}
                    </th>
                    <td>
                        {{ $media->title }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.article.fields.image') }}
                    </th>
                    <td>
                        {{ $media->image }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.article.fields.content') }}
                    </th>
                    <td>
                        {!! $media->content !!}
                    </td>
                </tr>

            </tbody>
        </table>
    </div>
</div>

@endsection