routes/web.php
<?php

// Route::redirect('/', '/login');

Route::redirect('/home', '/admin');
Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/profile/{slug}', 'WelcomeController@showpage');
Route::get('/about', 'WelcomeController@showabout');
Route::get('/member', 'WelcomeController@showmember');
Route::get('/result/{research}', 'WelcomeController@showdetailresearch');
Route::get('/article/{article}', 'WelcomeController@showdetailarticle');
// Route buat contoh article
Route::get('/article', 'WelcomeController@showarticle')->name('edusection.index');
Route::get('/article/subarticle/{id}', 'WelcomeController@showsubarticle')->name('subarticle.ind');
Route::get('/article/subarticle/detail/{subarticle}', 'WelcomeController@showdetail')->name('detailsub.show');
// Route buat supportus
Route::get('/support', 'WelcomeController@support');

Auth::routes(['register' => false]);
Route::get('logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('/');
})->name('logout');

Route::get('/search','WelcomeController@search');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');


    Route::resource('roles', 'RolesController');
;

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('contributes/destroy', 'ContributeController@massDestroy')->name('contributes.massDestroy');

    Route::resource('contributes', 'ContributeController');

    Route::delete('requests/destroy', 'RequestsController@massDestroy')->name('requests.massDestroy');

    Route::resource('requests', 'RequestsController');

    // Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    // Route::resource('products', 'ProductsController');

    // Route::resource('articles', 'ArticleController');

    // Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');


    // Route::resource('subarticles', 'SubArticleController');
    Route::get('subarticles/creates/{id}', 'SubArticleController@creates')->name('subarticles.creates');
    Route::get('subarticles/show/{subarticle}/detail', 'SubArticleController@show')->name('subarticles.shows');
    Route::get('subarticles/{subarticle}/edit', 'SubArticleController@edit')->name('subarticles.edit');
    Route::post('subarticles/store', 'SubArticleController@store')->name('subarticles.store');
    Route::get('subarticles/detail/{id}', 'SubArticleController@index')->name('subarticles.indexs');
    Route::post('subarticles/update', 'SubArticleController@update')->name('subarticles.update');
    Route::get('subarticles/{id}', 'SubArticleController@index')->name('subarticles.destroy');
    Route::delete('subarticles/destroy', 'SubArticleController@massDestroy')->name('subarticles.massDestroy');
    Route::resource('subarticles', 'SubArticleController');



    Route::resource('medias', 'MediaController');
    Route::delete('medias/destroy', 'MediaController@massDestroy')->name('medias.massDestroy');

    Route::resource('footers', 'FooterController');
    Route::delete('footers/destroy', 'FooterController@massDestroy')->name('footers.massDestroy');

    Route::resource('homes', 'HomePageController');
    Route::delete('homes/destroy', 'HomePageController@massDestroy')->name('homes.massDestroy');


    Route::resource('sliders', 'SliderController');
    Route::delete('sliders/destroy', 'SliderController@massDestroy')->name('sliders.massDestroy');

    Route::group(['prefix' => 'laravel-filemanager','middleware' => ['auth']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});


});
Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    //
      //
      use SoftDeletes;

      protected $dates = [
          'created_at',
          'updated_at',
          'deleted_at',
      ];
  
      protected $fillable = [
          'name',
          'image',
          'created_at',
          'updated_at',
          'deleted_at',
      ];
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroySliderRequest;
use App\Http\Requests\StoreSliderRequest;
use App\Http\Requests\UpdateSliderRequest;
use App\Slider;

class SliderController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('slider_access'), 403);

        $sliders = Slider::all();

        return view('admin.sliders.index', compact('sliders'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('slider_create'), 403);

        return view('admin.sliders.create');
    }

    public function store(StoreSliderRequest $request)
    {
        abort_unless(\Gate::allows('slider_create'), 403);

        $slider = Slider::create($request->all());

        return redirect()->route('admin.sliders.index');
    }

    public function edit(Slider $slider)
    {
        abort_unless(\Gate::allows('slider_edit'), 403);

        return view('admin.sliders.edit', compact('slider'));
    }

    public function update(UpdateSliderRequest $request, Slider $slider)
    {
        abort_unless(\Gate::allows('slider_edit'), 403);

        $slider->update($request->all());

        return redirect()->route('admin.sliders.index');
    }

    public function show(Slider $slider)
    {
        abort_unless(\Gate::allows('slider_show'), 403);

        return view('admin.sliders.show', compact('slider'));
    }

    public function destroy(Slider $slider)
    {
        abort_unless(\Gate::allows('slider_delete'), 403);

        $slider->delete();

        return back();
    }

    public function massDestroy(MassDestroySliderRequest $request)
    {
        Slider::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}

resources/views/admin/sliders/create.blade.php
@extends('layouts.admin')
@section('content')
<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.slider.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.sliders.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.slider.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($slider) ? $slider->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
            </div>
            
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                      <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                        <i class="fa fa-picture-o"></i> Choose
                      </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="image">
                  </div>
                  <img id="holder" style="margin-top:15px;max-height:100px;">
                  <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
                  <script>
                  var route_prefix = "http://127.0.0.1:8000/laravel-filemanager";
 $('#lfm').filemanager('image', {prefix: route_prefix});
                </script>
                </div>
            
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/sliders/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.user.title_singular') }}
    </div>

    <div class="card-body">
      <form action="{{ route("admin.sliders.update", [$slider->id]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')   
         <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.slider.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($slider) ? $slider->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
            </div>
            
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                      <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                        <i class="fa fa-picture-o"></i> Choose
                      </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="image" value="{{ old('image', isset($slider) ? $slider->image : '') }}">
                  </div>
                  <img id="holder" style="margin-top:15px;max-height:100px;">
                  <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
                  <script>
                  var route_prefix = "http://127.0.0.1:8000/laravel-filemanager";
 $('#lfm').filemanager('image', {prefix: route_prefix});
                </script>
                </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/sliders/index.blade.php
@extends('layouts.admin')
@section('content')
@can('user_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.sliders.create") }}">
                {{ trans('global.add') }} {{ trans('global.slider.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.slider.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('global.slider.fields.name') }}
                        </th>
                        <th>
                            {{ trans('global.slider.fields.image') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($sliders as $key => $slider)
                        <tr data-entry-id="{{ $slider->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $slider->name ?? '' }}
                            </td>
                            <td>
                               <img height="150" src=" {{ $slider->image ?? '' }}" alt="">
                            </td>
                            <td>
                                @can('slider_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.sliders.show', $slider->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('slider_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.sliders.edit', $slider->id) }}">
                                        {{ trans('global.edit') }} 
                                    </a>
                                @endcan
                                @can('slider_delete')
                                    <form action="{{ route('admin.sliders.destroy', $slider->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.users.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('user_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/sliders/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.user.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.slider.fields.name') }}
                    </th>
                    <td>
                        {{ $slider->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.slider.fields.image') }}
                    </th>
                    <td>
                       <img src=" {{ $slider->image }}" alt="">
                    </td>
                </tr>
                
            
            </tbody>
        </table>
    </div>
</div>

@endsection