routes/web.php
<?php

// Route::redirect('/', '/login');

Route::redirect('/home', '/admin');
Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/profile/{slug}', 'WelcomeController@showpage');
Route::get('/about', 'WelcomeController@showabout');
Route::get('/member', 'WelcomeController@showmember');
Route::get('/result/{research}', 'WelcomeController@showdetailresearch');
Route::get('/article/{article}', 'WelcomeController@showdetailarticle');
// Route buat contoh article
Route::get('/article', 'WelcomeController@showarticle')->name('edusection.index');
Route::get('/article/subarticle/{id}', 'WelcomeController@showsubarticle')->name('subarticle.ind');
Route::get('/article/subarticle/detail/{subarticle}', 'WelcomeController@showdetail')->name('detailsub.show');
// Route buat supportus
Route::get('/support', 'WelcomeController@support');

Auth::routes(['register' => false]);
Route::get('logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('/');
})->name('logout');

Route::get('/search','WelcomeController@search');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');


    Route::resource('roles', 'RolesController');
;

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('contributes/destroy', 'ContributeController@massDestroy')->name('contributes.massDestroy');

    Route::resource('contributes', 'ContributeController');

    Route::delete('requests/destroy', 'RequestsController@massDestroy')->name('requests.massDestroy');

    Route::resource('requests', 'RequestsController');

    // Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    // Route::resource('products', 'ProductsController');

    // Route::resource('articles', 'ArticleController');

    // Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');


    // Route::resource('subarticles', 'SubArticleController');
    Route::get('subarticles/creates/{id}', 'SubArticleController@creates')->name('subarticles.creates');
    Route::get('subarticles/show/{subarticle}/detail', 'SubArticleController@show')->name('subarticles.shows');
    Route::get('subarticles/{subarticle}/edit', 'SubArticleController@edit')->name('subarticles.edit');
    Route::post('subarticles/store', 'SubArticleController@store')->name('subarticles.store');
    Route::get('subarticles/detail/{id}', 'SubArticleController@index')->name('subarticles.indexs');
    Route::post('subarticles/update', 'SubArticleController@update')->name('subarticles.update');
    Route::get('subarticles/{id}', 'SubArticleController@index')->name('subarticles.destroy');
    Route::delete('subarticles/destroy', 'SubArticleController@massDestroy')->name('subarticles.massDestroy');
    Route::resource('subarticles', 'SubArticleController');



    Route::resource('medias', 'MediaController');
    Route::delete('medias/destroy', 'MediaController@massDestroy')->name('medias.massDestroy');

    Route::resource('footers', 'FooterController');
    Route::delete('footers/destroy', 'FooterController@massDestroy')->name('footers.massDestroy');

    Route::resource('homes', 'HomePageController');
    Route::delete('homes/destroy', 'HomePageController@massDestroy')->name('homes.massDestroy');


    Route::resource('sliders', 'SliderController');
    Route::delete('sliders/destroy', 'SliderController@massDestroy')->name('sliders.massDestroy');

    Route::group(['prefix' => 'laravel-filemanager','middleware' => ['auth']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});


});
Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();});

app/Home.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Home extends Model
{
    // use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'about',
        'video',
        'video_text',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Media;
use App\SubArticle;

class HomeController
{
    public function index()
    {
        $media = Media::latest()->get();
        $subarticle = SubArticle::latest()->get();
        return view('home',compact('media','subarticle'));
    }
    public function search(Request $request)
    {
        $search = $request->get('search');
        $articles = SubArticle::all()->where('title','like','%' .$search. '%')->paginate(5);
        return view('home',['articles' => $articles]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\Slider;
use App\Home;
use App\Founder;
use App\Partner;
use App\Page;
use App\Footer;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $pages = Page::all();
        $sliders = Slider::latest()->get();
        $homes = Home::all();
        $partners = Partner::all();
        $founders = Founder::all();
        $footers = Footer::all();
        return view('home',compact('pages','sliders','homes','partners','founders','footers'));
    }
}

resources/views/admin/homes/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.home.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.homes.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('about') ? 'has-error' : '' }}">
                <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
                <label for="name">{{ trans('global.home.fields.about') }}*</label>
                <textarea name="about" class="form-control my-editor"></textarea>
                <script>
                  var editor_config = {
                    path_absolute : "/",
                    selector: "textarea.my-editor",
                    plugins: [
                      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                      "searchreplace wordcount visualblocks visualchars code fullscreen",
                      "insertdatetime media nonbreaking save table contextmenu directionality",
                      "emoticons template paste textcolor colorpicker textpattern"
                    ],
                    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
                    relative_urls: false,
                    file_browser_callback : function(field_name, url, type, win) {
                      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
                
                      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                      if (type == 'image') {
                        cmsURL = cmsURL + "&type=Images";
                      } else {
                        cmsURL = cmsURL + "&type=Files";
                      }
                
                      tinyMCE.activeEditor.windowManager.open({
                        file : cmsURL,
                        title : 'Filemanager',
                        width : x * 0.8,
                        height : y * 0.8,
                        resizable : "yes",
                        close_previous : "no"
                      });
                    }
                  };
                
                  tinymce.init(editor_config);
                </script>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.home.fields.video') }}URL *</label>
                <input type="text" id="name" name="video" class="form-control" value="{{ old('video', isset($home) ? $home->video : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.home.fields.video_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('video_text') ? 'has-error' : '' }}">
                <label for="video_text">{{ trans('global.home.fields.video_text') }}*</label>
                <input type="video_text" id="video_text" name="video_text" class="form-control" value="{{ old('video_text', isset($home) ? $home->video_text : '') }}">
                @if($errors->has('video_text'))
                    <em class="invalid-feedback">
                        {{ $errors->first('video_text') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.home.fields.video_text_helper') }}
                </p>
            </div>
            
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/homes/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.home.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.homes.update", [$home->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('about') ? 'has-error' : '' }}">
                <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
                <label for="name">{{ trans('global.home.fields.about') }}*</label>
                <textarea name="about" class="form-control my-editor">
                  {!! old('about', isset($home) ? $home->about : '') !!}
                </textarea>
                <script>
                  var editor_config = {
                    path_absolute : "/",
                    selector: "textarea.my-editor",
                    plugins: [
                      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                      "searchreplace wordcount visualblocks visualchars code fullscreen",
                      "insertdatetime media nonbreaking save table contextmenu directionality",
                      "emoticons template paste textcolor colorpicker textpattern"
                    ],
                    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
                    relative_urls: false,
                    file_browser_callback : function(field_name, url, type, win) {
                      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
                
                      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                      if (type == 'image') {
                        cmsURL = cmsURL + "&type=Images";
                      } else {
                        cmsURL = cmsURL + "&type=Files";
                      }
                
                      tinyMCE.activeEditor.windowManager.open({
                        file : cmsURL,
                        title : 'Filemanager',
                        width : x * 0.8,
                        height : y * 0.8,
                        resizable : "yes",
                        close_previous : "no"
                      });
                    }
                  };
                
                  tinymce.init(editor_config);
                </script>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.home.fields.video') }}URL *</label>
                <input type="text" id="name" name="video" class="form-control" value="{{ old('video', isset($home) ? $home->video : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.home.fields.video_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('video_text') ? 'has-error' : '' }}">
                <label for="video_text">{{ trans('global.home.fields.video_text') }}*</label>
                <input type="video_text" id="video_text" name="video_text" class="form-control" value="{{ old('video_text', isset($home) ? $home->video_text : '') }}">
                @if($errors->has('video_text'))
                    <em class="invalid-feedback">
                        {{ $errors->first('video_text') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.home.fields.video_text_helper') }}
                </p>
            </div>
            
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/homes/index.blade.php
        @extends('layouts.admin')
@section('content')
@can('homepage_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.homes.create") }}">
                {{ trans('global.add') }} {{ trans('global.home.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.home.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('global.home.fields.about') }}
                        </th>
                        <th>
                            {{ trans('global.home.fields.video') }}
                        </th>
                        <th>
                            {{ trans('global.home.fields.video_text') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($homes as $key => $home)
                        <tr data-entry-id="{{ $home->id }}">
                            <td>

                            </td>
                            <td>
                                {!! $home->about ?? '' !!}
                            </td>
                            <td>
                                {{ $home->video ?? '' }}
                            </td>
                            <td>
                                {{ $home->video_text ?? '' }}
                            </td>
                            <td>
                                @can('homepage_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.homes.show', $home->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('homepage_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.homes.edit', $home->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('homepage_delete')
                                <form action="{{ route('admin.homes.destroy', $home->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>
                            @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.homes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('homepage_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/homes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.home.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.home.fields.about') }}
                    </th>
                    <td>
                        {!! $home->about !!}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.home.fields.video') }}
                    </th>
                    <td>
                            <iframe class="w-100" height="248" src="{{ $home->video }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.home.fields.video_text') }}
                    </th>
                    <td>
                        {{ $home->video_text }}
                    </td>
                </tr>
              
            </tbody>
        </table>
    </div>
</div>

@endsection